[manager]
ratio = [1, 1, 2]
show_hidden = true
show_symlink = true

[opener]
edit = [
	{ run = '$EDITOR "$@"', block = false, for = "unix" },
	{ run = "%EDITOR% %*",  block = false, for = "windows" },
]
